apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      {{- if .Values.affinity -}}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-app
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - db
            topologyKey: "kubernetes.io/hostname"
      {{ end }}
      containers:
      - name: {{ .Release.Name }}-app
        image: {{ .Values.app.image }}
        ports: 
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: DB_USERNAME
          value: {{ .Values.mysql.auth.username }}
        - name: DB_DATABASE
          value: {{ .Values.mysql.auth.database }}
        - name: DB_PASSWORD
          value: {{ .Values.mysql.auth.password }}